version: "3"
services:
    database:
        image: postgres
        restart: unless-stopped
        env_file: .env
        networks:
            - internal

    api:
        build: api/
        restart: unless-stopped
        ports:
            - 3001:3000
        environment:
            - DATABASE_URL=postgres://postgres:uG3MoQG2g9bpyvGBrrhzzh8E@database:5432/postgres
            - JWT_SECRET=cutefluffykitties
        depends_on:
            - database
        networks:
            - internal

    mqtt-server:
        image: eclipse-mosquitto
        restart: unless-stopped
        ports:
            - 1883:1883
        volumes:
            - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./config/mosquitto/dynamic-security.json:/mosquitto/config/dynamic-security.json
            - mosquitto-data:/mosquitto/data

networks:
    internal:

volumes:
    mosquitto-data: